---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: bitnami/jupyterhub
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
